# Continious integration script for travis
language: python
python:
  - "2.7"
install: pip install -r requirements.txt
script:
  - nosetests tests/test_filter.py
  - nosetests tests/test_views_integration.py
  - nosetests tests/test_views_acceptance.py